In [2]:
import pandas as pd

df = pd.read_csv("nasdaq100_latest_raw_data.csv")
df.head()

,Date,Company,Open,High,Low,Close,Adj_Close,Volume,Dividends,Stock_Splits
0,1985-01-31 00:00:00-05:00,AAPL,0.133371,0.133929,0.129464,0.129464,0.099341,276236800,0.0,0.0
1,1985-02-01 00:00:00-05:00,AAPL,0.129464,0.130022,0.126674,0.127790,0.098057,137737600,0.0,0.0
2,1985-02-04 00:00:00-05:00,AAPL,0.130580,0.131138,0.130580,0.130580,0.100198,218019200,0.0,0.0
3,1985-02-05 00:00:00-05:00,AAPL,0.131696,0.133929,0.131696,0.131696,0.101054,190041600,0.0,0.0
4,1985-02-06 00:00:00-05:00,AAPL,0.133929,0.133929,0.133929,0.133929,0.102767,194432000,0.0,0.0

In [8]:
df[df.isna().all(axis=1)]

Empty DataFrame
Columns: [Date, Company, Open, High, Low, Close, Adj_Close, Volume, Dividends, Stock_Splits]
Index: []

In [32]:
df['date'] = pd.to_datetime(df['date'], utc=True).dt.tz_localize(None).dt.normalize()
df = df.sort_values(['date', 'Company'])
df = df.drop(columns=['Date'])
df = df.rename(columns={'date': 'Date'})
df.head()

,Company,Open,High,Low,Close,Adj_Close,Volume,Dividends,Stock_Splits,Date
0,AAPL,0.133371,0.133929,0.129464,0.129464,0.099341,276236800,0.0,0.0,1985-01-31
21388,ADI,3.343750,3.359375,3.296875,3.359375,2.066376,697600,0.0,0.0,1985-01-31
31659,ADP,2.211905,2.230493,2.187122,2.187122,1.083401,3104919,0.0,0.0,1985-01-31
52098,AEP,21.250000,21.375000,21.125000,21.375000,2.362735,192900,0.0,0.0,1985-01-31
62369,AMAT,0.273438,0.274414,0.273438,0.273438,0.198463,25126400,0.0,0.0,1985-01-31

In [43]:
prices = df.pivot(index='Date', columns='Company', values='Adj_Close')
min_years = 5
min_days = min_years * 252
prices = prices.dropna(axis=1, thresh=min_days)
df['Company'].unique()

array(['AAPL', 'ADI', 'ADP', 'AEP', 'AMAT', 'AMD', 'AMGN', 'CMCSA', 'CSX',
       'CTAS', 'EXC', 'HON', 'INTC', 'KLAC', 'LRCX', 'MU', 'PAYX', 'PCAR',
       'PEP', 'TXN', 'XEL', 'ADSK', 'ROST', 'MNST', 'MSFT', 'COST',
       'ADBE', 'CCEP', 'BKR', 'CDNS', 'FAST', 'EA', 'CSCO', 'REGN',
       'IDXX', 'VRTX', 'BIIB', 'ODFL', 'QCOM', 'GILD', 'ROP', 'SNPS',
       'LIN', 'SBUX', 'INTU', 'MCHP', 'ORLY', 'AZN', 'CPRT', 'ASML',
       'TTWO', 'AMZN', 'MAR', 'MSTR', 'CTSH', 'CSGP', 'NVDA', 'BKNG',
       'ON', 'ISRG', 'MRVL', 'MDLZ', 'AXON', 'NFLX', 'TRI', 'GOOG',
       'GOOGL', 'DXCM', 'WBD', 'TMUS', 'LULU', 'MELI', 'KDP', 'AVGO',
       'VRSK', 'FTNT', 'CHTR', 'TSLA', 'NXPI', 'META', 'PANW', 'FANG',
       'WDAY', 'CDW', 'SHOP', 'KHC', 'PYPL', 'TEAM', 'TTD', 'ZS', 'PDD',
       'CRWD', 'DDOG', 'PLTR', 'DASH', 'ABNB', 'APP', 'GFS', 'CEG',
       'GEHC', 'ARM', 'SOLS'], dtype=object)

In [51]:
df = df.sort_values(['Company', 'Date'])
df['Return'] = df.groupby('Company')['Adj_Close'].pct_change()
df = df.dropna(subset=['Return'])
df.head()

,Company,Open,High,Low,Close,Adj_Close,Volume,Dividends,Stock_Splits,Date,Return
1,AAPL,0.129464,0.130022,0.126674,0.127790,0.098057,137737600,0.0,0.0,1985-02-01,-0.012930
2,AAPL,0.130580,0.131138,0.130580,0.130580,0.100198,218019200,0.0,0.0,1985-02-04,0.021833
3,AAPL,0.131696,0.133929,0.131696,0.131696,0.101054,190041600,0.0,0.0,1985-02-05,0.008547
4,AAPL,0.133929,0.133929,0.133929,0.133929,0.102767,194432000,0.0,0.0,1985-02-06,0.016955
5,AAPL,0.133929,0.135603,0.133371,0.133371,0.102339,245481600,0.0,0.0,1985-02-07,-0.004166

In [53]:
df.to_csv('cleaned_stock_data.csv', index=False)